CUDA_VISIBLE_DEVICES=4 python test.py --camera kinect --dump_dir logs/log_kn/dump_epoch10 --checkpoint_path logs/log_kn/minkresunet_epoch10.tar --batch_size 1 --dataset_root /data3/graspnet --infer --eval --collision_thresh -1

nohup python test.py --camera realsense --dump_dir logs/log_dinov2_depth/dump_epoch400_novel_nocd --checkpoint_path logs/log_dinov2_depth/minkuresunet_epoch400.tar --batch_size 1 --dataset_root ./data3/graspnet --infer --eval --collision_thresh -1 > logs/log_dinov2_depth/dump_epoch400_novel_nocd/eval.log
nohup python test.py --camera realsense --dump_dir logs/log_dinov2_depth/dump_epoch400_novel --checkpoint_path logs/log_dinov2_depth/minkuresunet_epoch400.tar --batch_size 1 --dataset_root ./data3/graspnet --infer --eval > logs/log_dinov2_depth/dump_epoch400_novel/eval.log


#nohup python test.py --camera realsense --dump_dir logs/log_dinov2_depth/dump_epoch400_dinov2_novel_nocd --checkpoint_path logs/log_dinov2_depth/minkuresunet_epoch400.tar --batch_size 1 --dataset_root ./data3/graspnet --infer --eval --collision_thresh -1 > logs/log_dinov2_depth/dump_epoch400_novel_nocd/eval.log

nohup python test.py --camera realsense --dump_dir logs/log_dinov2_depth/dump_epoch400_dinov2_seen --checkpoint_path logs/log_dinov2_400/minkuresunet_epoch400.tar --batch_size 1 --dataset_root ./data3/graspnet --infer --eval > logs/log_dinov2_depth/dump_epoch400_dinov2_seen/eval.log &
nohup python test.py --camera realsense --dump_dir logs/log_dinov2_depth/dump_epoch400_dinov2_seen_nocd --checkpoint_path logs/log_dinov2_400/minkuresunet_epoch400.tar --batch_size 1 --dataset_root ./data3/graspnet --infer --eval  --collision_thresh -1 > logs/log_dinov2_depth/dump_epoch400_dinov2_seen_nocd/eval.log &

nohup python test.py --camera realsense --dump_dir logs/log_dinov2_depth/dump_epoch400_dinov2_similar --checkpoint_path logs/log_dinov2_400/minkuresunet_epoch400.tar --batch_size 1 --dataset_root ./data3/graspnet --infer --eval > logs/log_dinov2_depth/dump_epoch400_dinov2_similar/eval.log &
nohup python test.py --camera realsense --dump_dir logs/log_dinov2_depth/dump_epoch400_dinov2_similar_nocd --checkpoint_path logs/log_dinov2_400/minkuresunet_epoch400.tar --batch_size 1 --dataset_root ./data3/graspnet --infer --eval  --collision_thresh -1 > logs/log_dinov2_depth/dump_epoch400_dinov2_similar_nocd/eval.log &

nohup python test.py --camera realsense --dump_dir logs/log_dinov2_depth/dump_epoch400_similar --checkpoint_path logs/log_dinov2_depth/minkuresunet_epoch400.tar --batch_size 1 --dataset_root ./data3/graspnet --infer --eval > logs/log_dinov2_depth/dump_epoch400_similar/eval.log &
nohup python test.py --camera realsense --dump_dir logs/log_dinov2_depth/dump_epoch400_similar_nocd --checkpoint_path logs/log_dinov2_depth/minkuresunet_epoch400.tar --batch_size 1 --dataset_root ./data3/graspnet --infer --eval  --collision_thresh -1 > logs/log_dinov2_depth/dump_epoch400_similar_nocd/eval.log &
nohup python test.py --camera realsense --dump_dir logs/log_dinov2_depth/dump_epoch400_seen --checkpoint_path logs/log_dinov2_depth/minkuresunet_epoch400.tar --batch_size 1 --dataset_root ./data3/graspnet --infer --eval > logs/log_dinov2_depth/dump_epoch400_seen/eval.log &
nohup python test.py --camera realsense --dump_dir logs/log_dinov2_depth/dump_epoch400_seen_nocd --checkpoint_path logs/log_dinov2_depth/minkuresunet_epoch400.tar --batch_size 1 --dataset_root ./data3/graspnet --infer --eval  --collision_thresh -1 > logs/log_dinov2_depth/dump_epoch400_seen_nocd/eval.log &

#realsense*
CUDA_VISIBLE_DEVICES=7 nohup python test.py --camera realsense --dump_dir logs/log_dinov2_depth_agg/dump_epoch400_dinov2_seen --checkpoint_path logs/log_dinov2_400/minkuresunet_epoch400.tar --batch_size 1 --dataset_root ./data3/graspnet --infer --eval > logs/log_dinov2_depth_agg/dump_epoch400_dinov2_seen/eval.log &
CUDA_VISIBLE_DEVICES=9 nohup python test.py --camera realsense --dump_dir logs/log_dinov2_depth_agg/dump_epoch400_dinov2_seen_nocd --checkpoint_path logs/log_dinov2_400/minkuresunet_epoch400.tar --batch_size 1 --dataset_root ./data3/graspnet --infer --eval  --collision_thresh -1 > logs/log_dinov2_depth_agg/dump_epoch400_dinov2_seen_nocd/eval.log &
CUDA_VISIBLE_DEVICES=8 nohup python test.py --camera realsense --dump_dir logs/log_dinov2_depth_agg/dump_epoch400_dinov2_similar --checkpoint_path logs/log_dinov2_400/minkuresunet_epoch400.tar --batch_size 1 --dataset_root ./data3/graspnet --infer --eval > logs/log_dinov2_depth_agg/dump_epoch400_dinov2_similar/eval.log &
CUDA_VISIBLE_DEVICES=9 nohup python test.py --camera realsense --dump_dir logs/log_dinov2_depth_agg/dump_epoch400_dinov2_similar_nocd --checkpoint_path logs/log_dinov2_400/minkuresunet_epoch400.tar --batch_size 1 --dataset_root ./data3/graspnet --infer --eval  --collision_thresh -1 > logs/log_dinov2_depth_agg/dump_epoch400_dinov2_similar_nocd/eval.log &
CUDA_VISIBLE_DEVICES=8 nohup python test.py --camera realsense --dump_dir logs/log_dinov2_depth_agg/dump_epoch400_dinov2_novel --checkpoint_path logs/log_dinov2_400/minkuresunet_epoch400.tar --batch_size 1 --dataset_root ./data3/graspnet --infer --eval > logs/log_dinov2_depth_agg/dump_epoch400_dinov2_novel/eval.log &
CUDA_VISIBLE_DEVICES=9 nohup python test.py --camera realsense --dump_dir logs/log_dinov2_depth_agg/dump_epoch400_dinov2_novel_nocd --checkpoint_path logs/log_dinov2_400/minkuresunet_epoch400.tar --batch_size 1 --dataset_root ./data3/graspnet --infer --eval  --collision_thresh -1 > logs/log_dinov2_depth_agg/dump_epoch400_dinov2_novel_nocd/eval.log &

#kinect*
CUDA_VISIBLE_DEVICES=3 nohup python test.py --camera kinect --dump_dir logs/log_kinect_dinov2_depth/dump_epoch400_dinov2_seen --checkpoint_path logs/log_kinect_dinov2_400/minkuresunet_epoch400.tar --batch_size 1 --dataset_root ./data3/graspnet --infer --eval > logs/log_kinect_dinov2_depth/dump_epoch400_dinov2_seen/eval.log &
CUDA_VISIBLE_DEVICES=4 nohup python test.py --camera kinect --dump_dir logs/log_kinect_dinov2_depth/dump_epoch400_dinov2_seen_nocd --checkpoint_path logs/log_kinect_dinov2_400/minkuresunet_epoch400.tar --batch_size 1 --dataset_root ./data3/graspnet --infer --eval  --collision_thresh -1 > logs/log_kinect_dinov2_depth/dump_epoch400_dinov2_seen_nocd/eval.log &
CUDA_VISIBLE_DEVICES=3 nohup python test.py --camera kinect --dump_dir logs/log_kinect_dinov2_depth/dump_epoch400_dinov2_similar --checkpoint_path logs/log_kinect_dinov2_400/minkuresunet_epoch400.tar --batch_size 1 --dataset_root ./data3/graspnet --infer --eval > logs/log_kinect_dinov2_depth/dump_epoch400_dinov2_similar/eval.log &
CUDA_VISIBLE_DEVICES=4 nohup python test.py --camera kinect --dump_dir logs/log_kinect_dinov2_depth/dump_epoch400_dinov2_similar_nocd --checkpoint_path logs/log_kinect_dinov2_400/minkuresunet_epoch400.tar --batch_size 1 --dataset_root ./data3/graspnet --infer --eval  --collision_thresh -1 > logs/log_kinect_dinov2_depth/dump_epoch400_dinov2_similar_nocd/eval.log &
CUDA_VISIBLE_DEVICES=3 nohup python test.py --camera kinect --dump_dir logs/log_kinect_dinov2_depth/dump_epoch400_dinov2_novel --checkpoint_path logs/log_kinect_dinov2_400/minkuresunet_epoch400.tar --batch_size 1 --dataset_root ./data3/graspnet --infer --eval > logs/log_kinect_dinov2_depth/dump_epoch400_dinov2_novel/eval.log &
CUDA_VISIBLE_DEVICES=4 nohup python test.py --camera kinect --dump_dir logs/log_kinect_dinov2_depth/dump_epoch400_dinov2_novel_nocd --checkpoint_path logs/log_kinect_dinov2_400/minkuresunet_epoch400.tar --batch_size 1 --dataset_root ./data3/graspnet --infer --eval  --collision_thresh -1 > logs/log_kinect_dinov2_depth/dump_epoch400_dinov2_novel_nocd/eval.log &

#baseline* realsense
CUDA_VISIBLE_DEVICES=3 nohup python test.py --camera realsense --dump_dir logs/log_baseline_depth/dump_epoch300_seen --checkpoint_path logs/log_onecirclelr_300/minkuresunet_epoch300.tar --batch_size 1 --dataset_root ./data3/graspnet --infer --eval > logs/log_baseline_depth/dump_epoch300_seen/eval.log &
CUDA_VISIBLE_DEVICES=4 nohup python test.py --camera realsense --dump_dir logs/log_baseline_depth/dump_epoch300_seen_nocd --checkpoint_path logs/log_onecirclelr_300/minkuresunet_epoch300.tar --batch_size 1 --dataset_root ./data3/graspnet --infer --eval  --collision_thresh -1 > logs/log_baseline_depth/dump_epoch300_seen_nocd/eval.log &
CUDA_VISIBLE_DEVICES=3 nohup python test.py --camera realsense --dump_dir logs/log_baseline_depth/dump_epoch300_similar --checkpoint_path logs/log_onecirclelr_300/minkuresunet_epoch300.tar --batch_size 1 --dataset_root ./data3/graspnet --infer --eval > logs/log_baseline_depth/dump_epoch300_similar/eval.log &
CUDA_VISIBLE_DEVICES=4 nohup python test.py --camera realsense --dump_dir logs/log_baseline_depth/dump_epoch300_similar_nocd --checkpoint_path logs/log_onecirclelr_300/minkuresunet_epoch300.tar --batch_size 1 --dataset_root ./data3/graspnet --infer --eval  --collision_thresh -1 > logs/log_baseline_depth/dump_epoch300_similar_nocd/eval.log &
CUDA_VISIBLE_DEVICES=3 nohup python test.py --camera realsense --dump_dir logs/log_baseline_depth/dump_epoch300_novel --checkpoint_path logs/log_onecirclelr_300/minkuresunet_epoch300.tar --batch_size 1 --dataset_root ./data3/graspnet --infer --eval > logs/log_baseline_depth/dump_epoch300_novel/eval.log &
CUDA_VISIBLE_DEVICES=4 nohup python test.py --camera realsense --dump_dir logs/log_baseline_depth/dump_epoch300_novel_nocd --checkpoint_path logs/log_onecirclelr_300/minkuresunet_epoch300.tar --batch_size 1 --dataset_root ./data3/graspnet --infer --eval  --collision_thresh -1 > logs/log_baseline_depth/dump_epoch300_novel_nocd/eval.log &


#baseline* kinect s
CUDA_VISIBLE_DEVICES=3 nohup python test.py --camera kinect --dump_dir logs/log_kinect_baseline_depth/dump_epoch300_seen --checkpoint_path logs/log_kinect_base_300/minkuresunet_epoch300.tar --batch_size 1 --dataset_root ./data3/graspnet --infer --eval > logs/log_kinect_baseline_depth/dump_epoch300_seen/eval.log &
CUDA_VISIBLE_DEVICES=4 nohup python test.py --camera kinect --dump_dir logs/log_kinect_baseline_depth/dump_epoch300_seen_nocd --checkpoint_path logs/log_kinect_base_300/minkuresunet_epoch300.tar --batch_size 1 --dataset_root ./data3/graspnet --infer --eval  --collision_thresh -1 > logs/log_kinect_baseline_depth/dump_epoch300_seen_nocd/eval.log &
CUDA_VISIBLE_DEVICES=3 nohup python test.py --camera kinect --dump_dir logs/log_kinect_baseline_depth/dump_epoch300_similar --checkpoint_path logs/log_kinect_base_300/minkuresunet_epoch300.tar --batch_size 1 --dataset_root ./data3/graspnet --infer --eval > logs/log_kinect_baseline_depth/dump_epoch300_similar/eval.log &
CUDA_VISIBLE_DEVICES=4 nohup python test.py --camera kinect --dump_dir logs/log_kinect_baseline_depth/dump_epoch300_similar_nocd --checkpoint_path logs/log_kinect_base_300/minkuresunet_epoch300.tar --batch_size 1 --dataset_root ./data3/graspnet --infer --eval  --collision_thresh -1 > logs/log_kinect_baseline_depth/dump_epoch300_similar_nocd/eval.log &
CUDA_VISIBLE_DEVICES=3 nohup python test.py --camera kinect --dump_dir logs/log_kinect_baseline_depth/dump_epoch300_novel --checkpoint_path logs/log_kinect_base_300/minkuresunet_epoch300.tar --batch_size 1 --dataset_root ./data3/graspnet --infer --eval > logs/log_kinect_baseline_depth/dump_epoch300_novel/eval.log &
CUDA_VISIBLE_DEVICES=4 nohup python test.py --camera kinect --dump_dir logs/log_kinect_baseline_depth/dump_epoch300_novel_nocd --checkpoint_path logs/log_kinect_base_300/minkuresunet_epoch300.tar --batch_size 1 --dataset_root ./data3/graspnet --infer --eval  --collision_thresh -1 > logs/log_kinect_baseline_depth/dump_epoch300_novel_nocd/eval.log &